import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import "@radix-ui/themes/styles.css";
import { Text, Theme } from "@radix-ui/themes";
import Header from "./components/Header";
import Link from "next/link";

import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Intl",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: { locale: string };
}

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider messages={messages}>
          <Theme>
            <div className="flex flex-col min-h-screen max-w-4xl mx-auto p-4">
              <Header />
              <div className="mt-20">{children}</div>
            </div>
            <footer>
              <Text>&copy; 2024</Text>
            </footer>
          </Theme>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
